#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
matlab -nodisplay -r "addpath(genpath('.')); so_vcb_main"

# The previous version of this file was commented-out and follows below:
#
# matlab -nodisplay -r "addpath(genpath('.')); mo_vcb_main"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # matlab -nodisplay -r "addpath(genpath('.')); mo_vcb_main"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # matlab -nodisplay -r "addpath(genpath('.')); mo_vcb_main"
# # 
# 
